version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/ws"
    versions:
    - 7.4.0
    - 7.4.1
  - dependency-name: "@graphql-codegen/typescript"
    versions:
    - 1.20.2
    - 1.21.0
    - 1.21.1
  - dependency-name: "@graphql-codegen/typescript-operations"
    versions:
    - 1.17.14
    - 1.17.15
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: yup
    versions:
    - 0.32.8
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
    - 3.9.0
  - dependency-name: "@graphql-codegen/cli"
    versions:
    - 1.20.1
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: query-string
    versions:
    - 6.13.8
  - dependency-name: "@types/yup"
    versions:
    - 0.29.11
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: formik-material-ui-pickers
    versions:
    - 0.0.12
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: "@graphql-codegen/typescript-react-apollo"
    versions:
    - 2.2.1
  - dependency-name: object-path
    versions:
    - 0.11.5
  - dependency-name: acorn
    versions:
    - 6.4.2
  - dependency-name: "@apollo/react-hooks"
    versions:
    - 4.0.0
  - dependency-name: graphql
    versions:
    - 14.7.0
  - dependency-name: gatsby-plugin-material-ui
    versions:
    - 2.1.10
